From nginx:1.17.5-alpine
RUN mkdir /usr/share/nginx/html/static
COPY ./start.sh /usr/local/bin/start.sh
COPY ./nginx.tpl /etc/nginx/nginx.tpl
ENV PORT 80
ENV APP_SERVER "http://127.0.0.1:8080"
CMD ["/usr/local/bin/start.sh"]